sudo: false
language: python
cache: pip
python:
  - 3.6

env:
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=doctest

install:
  - travis_retry pip install tox
script:
  - tox
after_success:
  - [[ $TOXENV == py36 ]] && coveralls
