sudo: false
language: python
cache: pip
python:
  - 3.6

env:
  - TOXENV=py36
  - TOXENV=flake8
  - TOXENV=doctest

install:
  - travis_retry pip install tox
  - if [[ $TOXENV == py36 ]]; then travis_retry pip install coveralls; fi
script:
  - tox
after_success:
  - if [[ $TOXENV == py36 ]]; then coveralls; fi
